### ISSUE TITLE
Can't get it running.

### ISSUE THREAD

**Issue by deannick** [andrewwippler/rpi-wayfinding#17]
At the point of editing rpi-wayfinding.sh.  It says Contents (where BOLD is the same as inside rooms.php).  I dont see any bold words. I dont know if that is what im missing to get this to work or not but this is the only thing that i have completed correctly.  When i the the rpi.wayfinding.sh i get feh ERROR: Can't open X display. It _is_ running, yeah?  Any help on this would be great.

**Comment by andrewwippler** [comment]
RPI-Wayfinding is meant to be used with LXDE as a window manager. This assumes you have xserver and the LXDE desktop environment already installed.

On Raspbian, you can install those items by doing a: **apt-get install xserver-xorg xinit xserver-org-video-fbdev lxde lxde-common**

You may also have re-do **raspi-config** and select boot to desktop.

**Comment by deannick** [comment]
Both of these are already on the current version.

**Comment by deannick** [comment]
I just realized that those messages are coming from me trying to start it from SSH.  When trying from the PI itself i get FEH warning, open url could not resolve host:webserver

**Comment by andrewwippler** [comment]
You will need to edit __/home/pi/rpi-wayfinding.sh__ with the correct URL to your webserver hosting RPi-wayfinding.

**Comment by deannick** [comment]
by changing webserver to localhost should work then?  The web server itself is running on the pi correct?

**Comment by andrewwippler** [comment]
Yes, if the webserver was installed on the pi, then it should be http://localhost/

**Comment by deannick** [comment]
what is looks like is the crontab is not working as it should.  Im looking in /www/images/ and dont see other things other than special-names and special-times.  Neither of these have anything either

**Comment by deannick** [comment]
if i run curl --silent --compressed http://localhost/cron_daily.php, i displays the php file.

**Comment by andrewwippler** [comment]
That command should return nothing. It sounds like the webserver is not processing php as a script but rather displaying it. Ensure php5-common is installed and restart apache:

sudo apt-get install php5-common
sudo service apache restart

**Comment by deannick** [comment]
php5-common said it was on the newest version when i ran the command

**Comment by andrewwippler** [comment]
Maybe it is that the apache module for php5 is not installed? Try:

**sudo apt-get install php5 libapache2-mod-php5**

Then restart apache.

**Comment by deannick** [comment]
that was the ticket it for it not showing the PHP file.  daily spits out 
php-ews/EWS/Exception.php<br>/ and regularly does nothing.  Still nothing in the images directory or in either of the special times or names.

**Comment by andrewwippler** [comment]
I believe this is an issue with the EWS auto-loader in  cron_daily.php. Can you comment out lines 7-14 of cron_daily.php and see if that populates the database?

**Comment by andrewwippler** [comment]
Also, can I get the outputs of 
```
tail /var/log/apache/error.log
```

**Comment by deannick** [comment]
[Wed Dec 30 19:42:19.566488 2015] [mpm_prefork:notice] [pid 3547] AH00163: Apache/2.4.10 (Raspbian) configured -- resuming normal operations
[Wed Dec 30 19:42:19.566994 2015] [core:notice] [pid 3547] AH00094: Command line: '/usr/sbin/apache2'
[Wed Dec 30 19:42:25.716050 2015] [:error] [pid 3551] [client ::1:32912] PHP Fatal error:  Class 'EWS_Exception' not found in /var/www/php-ews/ExchangeWebServices.php on line 729
[Wed Dec 30 19:43:44.047169 2015] [:error] [pid 3552] [client ::1:32914] PHP Parse error:  syntax error, unexpected 'id' (T_STRING) in /var/www/cron_regularly.php on line 379
[Wed Dec 30 19:46:01.243783 2015] [:error] [pid 3553] [client ::1:32915] PHP Parse error:  syntax error, unexpected 'id' (T_STRING) in /var/www/cron_regularly.php on line 379
[Wed Dec 30 19:46:01.243789 2015] [:error] [pid 3554] [client ::1:32916] PHP Parse error:  syntax error, unexpected 'id' (T_STRING) in /var/www/cron_regularly.php on line 379
[Wed Dec 30 20:01:01.400707 2015] [:error] [pid 3555] [client ::1:32918] PHP Parse error:  syntax error, unexpected 'id' (T_STRING) in /var/www/cron_regularly.php on line 379
[Wed Dec 30 20:01:01.406011 2015] [:error] [pid 3567] [client ::1:32919] PHP Parse error:  syntax error, unexpected 'id' (T_STRING) in /var/www/cron_regularly.php on line 379
[Wed Dec 30 20:16:01.883207 2015] [:error] [pid 3552] [client ::1:32921] PHP Parse error:  syntax error, unexpected 'id' (T_STRING) in /var/www/cron_regularly.php on line 379
[Wed Dec 30 20:16:01.887818 2015] [:error] [pid 3551] [client ::1:32920] PHP Parse error:  syntax error, unexpected 'id' (T_STRING) in /var/www/cron_regularly.php on line 379

**Comment by deannick** [comment]
i put /* at the beginning of 7 then */ at 14. daily does not spit anything back out.  Did you want me to look at the images dir?

**Comment by andrewwippler** [comment]
Looks like I had a typo cron_regularly.php I just fixed it with commit 9736be2

**Comment by deannick** [comment]
i corrected this in my file.

**Comment by deannick** [comment]
[Wed Dec 30 20:32:40.860959 2015] [:error] [pid 3552] [client ::1:32928] PHP Warning:  file_put_contents(/var/www/images/execconf.png): failed to open stream: Permission denied in /var/www/cron_regularly.php on line 185
[Wed Dec 30 20:32:40.872942 2015] [:error] [pid 3552] [client ::1:32928] PHP Warning:  file_put_contents(/var/www/images/second floor.png): failed to open stream: Permission denied in /var/www/cron_regularly.php on line 316
[Wed Dec 30 20:32:52.455171 2015] [:error] [pid 3551] [client ::1:32929] PHP Fatal error:  Class 'EWS_Exception' not found in /var/www/php-ews/ExchangeWebServices.php on line 729

**Comment by andrewwippler** [comment]
Let's give the webserver write permissions to that folder:
```
chmod 0775 /var/www/images -R
```

**Comment by deannick** [comment]
[Wed Dec 30 20:43:25.092276 2015] [:error] [pid 3554] [client ::1:32934] PHP Warning:  file_put_contents(/var/www/images/execconf.png): failed to open stream: Permission denied in /var/www/cron_regularly.php on line 185
[Wed Dec 30 20:43:25.093464 2015] [:error] [pid 3554] [client ::1:32934] PHP Warning:  file_put_contents(/var/www/images/second floor.png): failed to open stream: Permission denied in /var/www/cron_regularly.php on line 316

**Comment by andrewwippler** [comment]
What does a **ls -l /var/www** output ?

**Comment by deannick** [comment]
total 124
-rw-r--r-- 1 root root   802 Dec 29 20:08 clean.php
-rwxr-xr-x 1 root root  2329 Dec 30 20:22 cron_daily.php
-rwxr-xr-x 1 root root 10644 Dec 30 20:32 cron_regularly.php
-rwxr-xr-x 1 root root  3427 Dec 29 20:08 exchange.php
-rwxr-xr-x 1 root root  1253 Dec 29 20:08 force_sync.php
-rwxr-xr-x 1 root root  1264 Dec 29 20:08 google-calendar.php
drwxr-xr-x 2 root root  4096 Dec 30 14:51 html
-rwxr-xr-x 1 root root  1320 Dec 29 20:08 image.php
drwxrwxr-x 4 root root  4096 Dec 29 20:08 images
-rwxr-xr-x 1 root root    71 Dec 29 20:08 index.php
-rwxr-xr-x 1 root root  1840 Dec 29 20:08 install.php
-rwxr-xr-x 1 root root 18026 Dec 29 20:08 LICENSE
-rw-r--r-- 1 root root     6 Dec 29 20:08 login.php
drwxr-xr-x 5 root root  4096 Dec 29 20:08 php-ews
-rwxr-xr-x 1 root root  1669 Dec 29 20:08 planning-center.php
drwxr-xr-x 3 root root  4096 Dec 29 20:08 puppet
-rwxr-xr-x 1 root root  4377 Dec 29 20:08 README.md
-rwxr-xr-x 1 root root  1136 Dec 30 19:09 rooms.php
-rwxr-xr-x 1 root root  1174 Dec 29 23:39 rooms.php.save
-rwxr-xr-x 1 root root   660 Dec 29 20:42 settings.php
-rwxr-xr-x 1 root root    92 Dec 29 20:08 special_names.php
-rwxr-xr-x 1 root root   747 Dec 29 20:08 special_times.php
drwxr-xr-x 4 root root  4096 Dec 29 20:08 theme
-rwxr-xr-x 1 root root   201 Dec 29 20:08 theme_settings.php

**Comment by andrewwippler** [comment]
run this to make the webserver to have group permissions on files and folders: **chgrp www-data /var/www -R**

**Comment by deannick** [comment]
the images are now in the correct folder.  by commenting out 7-14 of cron_daily.php will this cause the EWS with exchange not to work?

**Comment by deannick** [comment]
this is from running the cron_daily

[Wed Dec 30 21:52:29.836456 2015] [:error] [pid 3552] [client ::1:32955] PHP Fatal error:  Class 'EWS_Exception' not found in /var/www/php-ews/ExchangeWebServices.php on line 729
pi@ras

**Comment by andrewwippler** [comment]
The autoload function is not necessary due to my including the required files for EWS already.

What is the output of **curl -V**

**Comment by deannick** [comment]
curl 7.38.0 (arm-unknown-linux-gnueabihf) libcurl/7.38.0 OpenSSL/1.0.1k zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP

**Comment by andrewwippler** [comment]
Looks like I have a more recent version of php-ews than what I included in my repo. Here is how to update it to the latest version:
```
cd /var/www
rm -rf php-ews/
git clone git@github.com:jamesiarmes/php-ews.git php-ews
```

**Comment by deannick** [comment]
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by andrewwippler** [comment]
Try the https version:
```
git clone https://github.com/jamesiarmes/php-ews.git php-ews
```

**Comment by deannick** [comment]
this worked

**Comment by deannick** [comment]
still with the daily  i get this 

[Wed Dec 30 23:05:23.497137 2015] [:error] [pid 3567] [client ::1:32971] PHP Fatal error:  Class 'EWS_Exception' not found in /var/www/php-ews/ExchangeWebServices.php on line 1221

**Comment by andrewwippler** [comment]
Are the images generating properly? Are you able to log in via owa as the
user and see the calendar?

**Comment by deannick** [comment]
sudo ls /var/www/images/
corp.png  execconf.png  second floor.png  special-names  special-times

sudo ls /var/www/images/special-times/
FLOOR AND BLDG SPECIAL GO HERE

sudo ls /var/www/images/special-names/
PLACE CUSTOM HERE

**Comment by andrewwippler** [comment]
That looks proper. Does corp.png display the expected output?

**Comment by deannick** [comment]
i just seen that the account i was using is disabled.  im working with the AD admin to confirm that i can enable the account.  Im going to try this tomorrow i hope, or it will have to wait until next week.

**Comment by andrewwippler** [comment]
It is disabled because there is no password assigned. This is default behavior when creating room resources in exchange. It will not affect anything (as far as I can tell) if you assign a strong password to the account and enable it. Make sure the password doesn't expire or you will have to update the script with the new password.

**Comment by deannick** [comment]
thats good to know.  Im working on it remote right now.  I dont think x display will work through VNC.

**Comment by deannick** [comment]
the account im using is able to log into OWA

**Comment by andrewwippler** [comment]
So do the image files contain the events or is it the RPI way finding logo?

**Comment by deannick** [comment]
Displayed a pink screen

**Comment by andrewwippler** [comment]
When the signs are off, they display a solid color. This is to keep the LCD quality over long periods of time without burn-in. 

cron_regularly.php creates the images and cleans up the database. If there is nothing in the database, you will see the default rpiwayfinding logo (during hours).

**Comment by deannick** [comment]
right now it shows the rpiwayfinding logo

**Comment by deannick** [comment]
is there anything that needs to be setup on the exchange side for this to work?  I have a working room account that can log into OWA and see email and the calendar.

**Comment by andrewwippler** [comment]
Nothing special is needed on the exchange server. You only need a username and password to connect to the calendar of that user.

If there are Calendar events on that user's calendar, cron_daily.php will gather those and place them in the events table. cron_regularly.php deletes old events and cleans up the database while generating the image files.

Since the RPi-Wayfinding logo is showing, it means there are no events in the database for that specific room.

**Comment by deannick** [comment]
i added an event to the calendar for today and tomorrow

**Comment by deannick** [comment]
i ran cron_daily.php just to make sure it did run.  Is there a log that show that it logged in?

**Comment by andrewwippler** [comment]
There is no successful login message. If there are errors, it would be in
the apache error log.

Can you reply with your rooms.php (without the passwords) as well as the
link you are trying to view?

I will push a troubleshooting.php later today to help aid in finding the
issue.

**Comment by deannick** [comment]
$rooms = array();

$rooms[] = array(
                'name' => 'ExecConf', //Use - instead of spaces. This is case-s$
                'type' => 1, //1 = exchange room resource, 2 = planning center $
                'logon_name' => 'test', //for exchange room
                'pass' => '', //for exchange room
                'url' => '', //planning center/google calendar
                'group' => 'second floor', //first floor, building-first-floor,$
                'rpi' => array ('raspberrypi'), //place your hostnames here.
                'bldg' => 'Corp', //do not leave emtpy
                );

**Comment by deannick** [comment]
http://localhost/image.php?b=execconf&

**Comment by andrewwippler** [comment]
Based upon your rooms.php, your urls would look like:

http://localhost/image.php?i=raspberrypi
http://localhost/image.php?b=Corp
http://localhost/image.php?g=second%20floor

**Comment by deannick** [comment]
All three of them need to be there?

**Comment by andrewwippler** [comment]
No, if you just want the room (for outside of the room), you would use the first line. For a building lobby, you would use the second line. For a floor lobby sign, you would use the third line.

**Comment by deannick** [comment]
i am trying the first one and still getting just the logo.

**Comment by andrewwippler** [comment]
Do any of the images in the /images/ folder have anything other than the default logo?

**Comment by deannick** [comment]
corp is a yellow box and the other 2 are the logo
